# Generated by Django 2.2 on 2020-03-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='roles',
            field=models.IntegerField(choices=[(1, 'SuperAdmin'), (2, 'Guest')], default=2),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
