# Generated by Django 2.2 on 2020-04-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='due_date',
        ),
    ]
